### ISSUE TITLE
error and enhancement when executing "Horizontal Federated Tasks"

### ISSUE THREAD

**Issue by winterpi** [delta-mpc/delta-all-in-one#14]
配置好了delta-all-in-one ，在deltaboard中按照指示执行“横向联邦学习”及“横向联邦统计”的样例

### error in “横向联邦学习”
2个节点，2轮round执行没问题，但aggregate的时候出现“unsupported operand type(s) for ** or pow(): 'int' and 'str'” 错误。

在node1 & node2 的日志中显示如下：
![image](https://user-images.githubusercontent.com/89500827/195036622-7c2b3172-ccd4-4965-a78c-6d104b26b2ba.png)

### enhancement in “横向联邦统计”
按照指示构建task，且执行正确，但"download result"之后，result的文件无法查看，如下：
![image](https://user-images.githubusercontent.com/89500827/195038791-42a4d0df-e6d3-4a42-ae5b-24cdcc70c97c.png)

**Comment by lencyforce** [comment]
enhancement in “横向联邦统计” 
--> Result file should be loaded using pickle. Which is described in the developer docs.

**Comment by winterpi** [comment]
Thanks, I got it. 
but if it will be great if it can be read directly.

**Comment by mh739025250** [comment]
@winterpi 

你运行的delta-all-in-one是哪个版本，demo的文件是哪个，有没有自己修改过，告诉我一下，我定位下问题

**Comment by winterpi** [comment]
0.8.0，横向联邦学习，没有任何修改

**Comment by mh739025250** [comment]
@winterpi 已经在0.8.1版本修复了这个问题
