### ISSUE TITLE
编译及部署智能合约过程的问题

### ISSUE THREAD

**Issue by Brumairef** [delta-mpc/delta-all-in-one#15]
根据指导文档 https://docs.deltampc.com/network-deployment/deploy-smart-contracts 的步骤，到使用 _truffle migrate_ 编译并部署contracts目录下的智能合约时，出现了以下问题。
![image](https://user-images.githubusercontent.com/105054392/200186610-05ecc6cb-fb63-41a7-9917-cfccc4329883.png)
卡了好多天了 基础有些差 希望可以帮忙看一下问题呢

**Comment by lencyforce** [comment]
Truffle编译并部署合约后，会把上次部署的合约信息记录在build文件夹中，每次migration会在build文件夹中找到上次部署的Migration合约，检查是否已经migrate过了，如果migration文件没有修改，重复部署，就会提示Everything is up to date。线下测试的话，每次修改了合约，直接把build文件夹删除再部署就好了

**Comment by lencyforce** [comment]
[#delta-contracts/issues/13](https://github.com/delta-mpc/delta-contracts/issues/13)
