### ISSUE TITLE
使用allinone镜像部署时遇到的问题

### ISSUE THREAD

**Issue by ssyyxx17410103151207** [delta-mpc/delta-all-in-one#16]
![image](https://user-images.githubusercontent.com/72251903/207212044-cc61f6fc-0d68-4615-9be5-69854419a924.png)

**Comment by mh739025250** [comment]
看起来是docker compose版本的问题，你docker compose的版本是多少？

**Comment by ssyyxx17410103151207** [comment]
1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "delta-mpc/delta-all-in-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 使用allinone镜像部署时遇到的问题 (Issue #16)





 
看起来是docker compose版本的问题，你docker compose的版本是多少？

**Comment by ssyyxx17410103151207** [comment]
需要多少版本的docker-compose呢


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1617869473"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 上午10:36
***@***.***&gt;;

主题:&nbsp;回复： [delta-mpc/delta-all-in-one] 使用allinone镜像部署时遇到的问题 (Issue #16)










1617869473
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "delta-mpc/delta-all-in-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 使用allinone镜像部署时遇到的问题 (Issue #16)





 
看起来是docker compose版本的问题，你docker compose的版本是多少？

**Comment by mh739025250** [comment]
docker版本19.03.0+，docker-compose版本1.29.2+

**Comment by ssyyxx17410103151207** [comment]
好的，谢谢




1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "delta-mpc/delta-all-in-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 使用allinone镜像部署时遇到的问题 (Issue #16)





 
docker版本19.03.0+，docker-compose版本1.29.2+
