### ISSUE TITLE
准备节点数据时遇到的问题

### ISSUE THREAD

**Issue by ssyyxx17410103151207** [delta-mpc/delta-all-in-one#17]

**Comment by mh739025250** [comment]
遇到什么问题呢

**Comment by ssyyxx17410103151207** [comment]
![image](https://user-images.githubusercontent.com/72251903/218621537-d50e38e4-868e-454d-95f0-a6eeaac4aa2f.png)
准备节点数据时遇到的问题如下，请问该怎么办

**Comment by ssyyxx17410103151207** [comment]
这个问题


&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
遇到什么问题呢

**Comment by mh739025250** [comment]
使用这个命令来初始化配置文件 `docker run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init`

**Comment by mh739025250** [comment]
你之前刚刚初始化配置文件的命令有点问题，用的是dev镜像，不是0.8.1。
顺便问一下，你这条初始化配置的命令是哪个文档里看到的？

**Comment by ssyyxx17410103151207** [comment]
是在

准备节点数据这个里面看到的，链接是准备节点数据 - Delta (deltampc.com)
&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
你之前刚刚初始化配置文件的命令有点问题，用的是dev镜像，不是0.8.1。
 顺便问一下，你这条初始化配置的命令是哪个文档里看到的？

**Comment by mh739025250** [comment]
哦，我看到了，截图是吧。这截图没更新，我回头文档改一下。
你现在问题解决了吗

**Comment by ssyyxx17410103151207** [comment]
还没呢，我试了一下没试好
&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
哦，我看到了，截图是吧。这截图没更新，我回头文档改一下。
 你现在问题解决了吗

**Comment by mh739025250** [comment]
你先把之前的目录下的`config`文件夹删掉，再输入我刚刚给你的命令

**Comment by ssyyxx17410103151207** [comment]
没有config文件夹，然后输入命令之后好像进入了控制之类的


&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
你先把之前的目录下的config文件夹删掉，再输入我刚刚给你的命令

**Comment by ssyyxx17410103151207** [comment]
是不是应该是docker&nbsp;run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init config 啊


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "delta-mpc/delta-all-in-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
使用这个命令来初始化配置文件 docker run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init`

**Comment by mh739025250** [comment]
> 是不是应该是docker&nbsp;run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init config 啊 1617869473 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "delta-mpc/delta-all-in-one" ***@***.***&gt;; 发送时间:&nbsp;2023年2月14日(星期二) 上午10:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17) 使用这个命令来初始化配置文件 docker run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

并不需要加`config`。你给我看看你执行的截图？

**Comment by ssyyxx17410103151207** [comment]
执行之后就是这样，出现了一个让输入东西的三角
&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





  
是不是应该是docker&nbsp;run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init config 啊 1617869473 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "delta-mpc/delta-all-in-one" @.&gt;; 发送时间:&nbsp;2023年2月14日(星期二) 上午10:20 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17) 使用这个命令来初始化配置文件 docker run -it --rm -v ${PWD}:/app deltampc/delta-node:0.8.1 init` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
并不需要加config。你给我看看你执行的截图？

**Comment by mh739025250** [comment]
额，图呢？

**Comment by ssyyxx17410103151207** [comment]
这样可以看到了吗


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "delta-mpc/delta-all-in-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
额，图呢？

**Comment by mh739025250** [comment]
不行。。。
要不你还是在github里发图？

**Comment by ssyyxx17410103151207** [comment]
好的
&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
不行。。。
 要不你还是在github里发图？

**Comment by ssyyxx17410103151207** [comment]
![image](https://user-images.githubusercontent.com/72251903/218625632-529a3fb2-6607-4cbb-95b0-61fed1062e72.png)

**Comment by mh739025250** [comment]
额，你命令最后多了一个字符`，你发现了没

**Comment by ssyyxx17410103151207** [comment]
我发现了，现在好了，谢谢，不好意思刚才复制的邮箱里的

**Comment by mh739025250** [comment]
不客气。
问题解决了我关issue了。

**Comment by ssyyxx17410103151207** [comment]
嗯嗯好的
&nbsp;


1617869473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午10:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [delta-mpc/delta-all-in-one] 准备节点数据时遇到的问题 (Issue #17)





 
不客气。
 问题解决了我关issue了。
