### ISSUE TITLE
Can't access to curl http://localhost:8090 

### ISSUE THREAD

**Issue by smudag** [delta-mpc/delta-all-in-one#2]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/90293674/134596798-f56e8e3e-c856-4f69-8a00-03934f7d393c.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/90293674/134597177-f875e744-6132-4c5c-ab9b-8854d067fa14.png">

Fail to `curl http://localhost:8090`
<img width="562" alt="image" src="https://user-images.githubusercontent.com/90293674/134596735-ed1863e6-5077-4b22-b714-1e9847b98b05.png">
docker containers have all started
<img width="568" alt="image" src="https://user-images.githubusercontent.com/90293674/134596821-ca1924f0-1167-400f-80bd-2dfe6118dd66.png">

**Comment by mh739025250** [comment]
You should make this issue to delta-all-in-one repo. Close this issue.

**Comment by mh739025250** [comment]
A workaround: 
use ssh local port forwarding
`ssh -fNt -L 8090:{your-server-ip}:8090 {your-server-ssh-name}`

or just edit your host file to make localhost resolved to your server ip.

**Comment by lencyforce** [comment]
This is the same as [deltaboard#51](https://github.com/delta-mpc/deltaboard/issues/51)
