### ISSUE TITLE
demo中默认超时时间过短

### ISSUE THREAD

**Issue by TYTaO** [delta-mpc/delta-all-in-one#6]
![image](https://user-images.githubusercontent.com/39618490/161235460-bbfda2fc-86a2-4722-8412-fc415f89c1eb.png)

当将各组件分别部署时，由于计算时间超时，导致进行聚合时，部分结果未上传（在demo中表现为node2的计算结果还未上传），此时node1已经开始聚合然后报错：“not enough clients in start aggregation”。
建议在超时设置中进行强调或者在delta-node代码中加入更详细的日志显式表示等待计算的过程。

**Comment by lencyforce** [comment]
报错的日志需要丰富一下，下一个版本加上

**Comment by lencyforce** [comment]
related [delta-node#6](https://github.com/delta-mpc/delta-node/issues/6)
